- name: Run Linux host prerequisite tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_system == "Linux"

- name: Run macOS host prerequisite tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_system == "Darwin"

- name: Fail for unsupported host prerequisite platforms
  ansible.builtin.include_tasks: unsupported.yml
  when: ansible_system not in ["Linux", "Darwin"]
