- name: Run Linux Docker runtime tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_system == "Linux"

- name: Run macOS Docker runtime tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_system == "Darwin"

- name: Fail for unsupported Docker runtime platforms
  ansible.builtin.include_tasks: unsupported.yml
  when: ansible_system not in ["Linux", "Darwin"]
